apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prerequisites-schema-registry
  labels:
    app: schema-registry
    app.kubernetes.io/instance: prerequisites
spec:
  serviceName: "schema-registry"
  replicas: 1
  selector:
    matchLabels:
      app: schema-registry
  template:
    metadata:
      labels:
        app: schema-registry
        app.kubernetes.io/instance: prerequisites
    spec:
      containers:
        - name: schema-registry
          image: confluentinc/cp-schema-registry:7.4.0
          ports:
            - containerPort: 8081
          env:
            - name: SCHEMA_REGISTRY_HOST_NAME
              value: "schema-registry"
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: "prerequisites-kafka:9092"  # 실제 릴리스 이름으로 변경 필요
            - name: SCHEMA_REGISTRY_LISTENERS
              value: "http://0.0.0.0:8081"
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prerequisites-schema-registry
  labels:
    app: schema-registry
    app.kubernetes.io/instance: prerequisites
spec:
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
  selector:
    app: schema-registry
  type: ClusterIP