name: Release Charts

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'LICENSE'
      - 'NOTICE'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Add Helm Dependencies
        run: |
          for dir in charts/*/; do
            helm dependency build $dir
          done
         
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_repo_url: https://zeta9044.github.io/datahub-helm
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
